lidar_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 115200
    samp_rate: 9
    resolution_fixed: false
    singleChannel: true
    auto_reconnect: true
    reversion: false
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 8.0
    min_range: 0.01
    frequency: 10.0